### ISSUE TITLE
How To Fix This Error. Help

### ISSUE THREAD

**Issue by RootSh311** [termux/termux-apt-repo#12]
I Have Uploaded All The File To My Gitpage
After Adding Sources.list With Trused=Yes
After Giving Apt Update Command I Get This Error.Can Anyone Help Me
$ apt update
Hit:1 https://termux.net stable InRelease
Ign:3 https://dl.bintray.com/xeffyr/x11-packages x11 InRelease
Get:4 https://dl.bintray.com/xeffyr/x11-packages x11 Release [6055 B]
Hit:4 https://dl.bintray.com/xeffyr/x11-packages x11 Release
Ign:2 https://rootsh311.github.io/repo main InRelease
Ign:5 https://rootsh311.github.io/repo main Release
Ign:6 http://rootsh311.github.io/repo main/stable arm Packages
Ign:6 https://rootsh311.github.io/repo main/stable arm Packages
Ign:7 http://rootsh311.github.io/repo main/stable all Packages
Ign:7 https://rootsh311.github.io/repo main/stable all Packages
Ign:6 http://rootsh311.github.io/repo main/stable arm Packages
Ign:6 https://rootsh311.github.io/repo main/stable arm Packages
Ign:7 http://rootsh311.github.io/repo main/stable all Packages
Ign:7 https://rootsh311.github.io/repo main/stable all Packages
Ign:6 http://rootsh311.github.io/repo main/stable arm Packages
Ign:6 https://rootsh311.github.io/repo main/stable arm Packages
Ign:7 http://rootsh311.github.io/repo main/stable all Packages
Ign:7 https://rootsh311.github.io/repo main/stable all Packages
Err:6 http://rootsh311.github.io/repo main/stable arm Packages
  404
Ign:6 https://rootsh311.github.io/repo main/stable arm Packages
Ign:7 https://rootsh311.github.io/repo main/stable all Packages
Reading package lists... Done
E: Failed to fetch http://rootsh311.github.io/repo/dists/main/stable/binary-arm/Packages  404
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by xeffyr** [comment]
> https://rootsh311.github.io/repo/dists/main/stable/binary-arm/Packages

You have typo in sources.list file.
Try something like
```
deb [trusted=yes] https://rootsh311.github.io/repo/ stable main
```

**Comment by xeffyr** [comment]
Closing as config from https://github.com/termux/termux-apt-repo/issues/12#issuecomment-467970769 works.

**Comment by RootSh311** [comment]
I Have Tried But Not Working. Can You Say How To Sign PUB key And Gpg

**Comment by xeffyr** [comment]
Seriously ? I just installed ngrok from YOUR repo :)
```
[~]:$ dpkg --add-architecture arm
[~]:$ cat $PREFIX/etc/apt/sources.list
# The main termux repository:
deb https://termux.net stable main

# rootsh311 repo
deb [trusted=yes] https://rootsh311.github.io/repo/ stable main
[~]:$ apt update
Hit:1 https://termux.net stable InRelease
Ign:2 https://rootsh311.github.io/repo stable InRelease
Hit:3 https://rootsh311.github.io/repo stable Release
Ign:4 https://dl.bintray.com/xeffyr/unstable-packages unstable InRelease
Ign:5 https://rootsh311.github.io/repo stable Release.gpg
Get:6 https://dl.bintray.com/xeffyr/unstable-packages unstable Release [6065 B]
Hit:6 https://dl.bintray.com/xeffyr/unstable-packages unstable Release
Get:7 https://rootsh311.github.io/repo stable/main arm Packages [472 B]
Get:8 https://termux.net stable/main arm Packages [66.3 kB]
Get:10 https://dl.bintray.com/xeffyr/unstable-packages unstable/main arm Packages [17.9 kB]
Fetched 84.6 kB in 3s (27.6 kB/s) 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
15 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Skipping acquire of configured file 'main/binary-aarch64/Packages' as repository 'https://rootsh311.github.io/repo stable InRelease' doesn't support architecture 'aarch64'
[~]:$ apt install ngrok
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  fontconfig libgd libwebp php
The following NEW packages will be installed:
  fontconfig libgd libwebp ngrok php
0 upgraded, 5 newly installed, 0 to remove and 15 not upgraded.
Need to get 11.3 MB of archives.
After this operation, 43.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://termux.net stable/main aarch64 fontconfig aarch64 2.13.1-1 [93.7 kB]
Get:2 https://termux.net stable/main aarch64 libwebp aarch64 1.0.2 [108 kB]
Get:3 https://termux.net stable/main aarch64 libgd aarch64 2.2.5-1 [89.1 kB]
Get:4 https://termux.net stable/main aarch64 php aarch64 7.3.2 [7469 kB]
Get:5 https://rootsh311.github.io/repo stable/main all ngrok all 1.0b [3537 kB]
Fetched 11.3 MB in 1s (9080 kB/s)                             
Selecting previously unselected package fontconfig.
(Reading database ... 17805 files and directories currently installed.)
Preparing to unpack .../fontconfig_2.13.1-1_aarch64.deb ...
Unpacking fontconfig (2.13.1-1) ...
Selecting previously unselected package libwebp.
Preparing to unpack .../libwebp_1.0.2_aarch64.deb ...
Unpacking libwebp (1.0.2) ...
Selecting previously unselected package libgd.
Preparing to unpack .../libgd_2.2.5-1_aarch64.deb ...
Unpacking libgd (2.2.5-1) ...
Selecting previously unselected package php.
Preparing to unpack .../archives/php_7.3.2_aarch64.deb ...
Unpacking php (7.3.2) ...
Selecting previously unselected package ngrok.
Preparing to unpack .../archives/ngrok_1.0b_all.deb ...
Unpacking ngrok (1.0b) ...
Setting up libwebp (1.0.2) ...
Setting up fontconfig (2.13.1-1) ...
Setting up libgd (2.2.5-1) ...
Setting up php (7.3.2) ...
Setting up ngrok (1.0b) ...
Processing triggers for man (1.14.4) ...
```

**Comment by RootSh311** [comment]
yeah Its working. Thank you

**Comment by datawithvishal** [comment]
Thanks. It is now <a href="https://onegyd.com/fix-xampp-install-uac-error-windows/">working</a>.

**Comment by NoobXoX** [comment]
i cant understand it, can u specify it for me please?
