### ISSUE TITLE
Unable to install or update 

### ISSUE THREAD

**Issue by ParaDoxX08** [termux/termux-apt-repo#14]
pkg install nano proot
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease                                           Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:4 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable InRelease
Err:5 https://dl.bintray.com/termux/termux-packages-24 stable Release
  403  Forbidden                                        Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:8 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:8 https://dl.bintray.com/grimler/science-packages-24 science Release
Get:10 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release [6065 B]                             Hit:10 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release
Reading package lists... Done
E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I am getting this error please help.
Thank you

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/4358

**Comment by abdou237** [comment]
Help please when I try to update or upgrade on termux I have this problem 
: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://termux.org/packages stable Release' does no longer have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by abdou237** [comment]
Help please when I try to update or upgrade on termux I have this problem 
: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://termux.org/packages stable Release' does no longer have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by Grimler91** [comment]
See https://github.com/termux/termux-packages/issues/6726
