### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-apt-repo#18]
Help, create a repository and use GitHub pages, and I do everything to the letter, but when I put pkg update I get this error :  
![Screenshot_20210414-164953](https://user-images.githubusercontent.com/64093255/114785088-c7799080-9d41-11eb-98c6-5eb928b7b22a.png)
![Screenshot_20210414-165019](https://user-images.githubusercontent.com/64093255/114785103-cba5ae00-9d41-11eb-8813-d90745b4a343.png)

**Comment by xeffyr** [comment]
Replace
* `yisus.ports` with `yisus.ports/main`
* `main dists` with `termux extras`

**Comment by Yisus7u7** [comment]
Thank you, I thank you very much, is my first time with this repositories thing, there is almost no documentation of this, another question, if I am going to upload a package to the repository, should I delete the folder with the content and upload it again?

**Comment by Yisus7u7** [comment]
Hello again, sorry for the hassle, as I do for termux-apt-repo to create the architecture folders
example: binaries-all binaries-armhf, etc...?
