### ISSUE TITLE
apt error parse

### ISSUE THREAD

**Issue by Kry9toN** [termux/termux-apt-repo#24]
E: Problem parsing dependency 20 of package:aarch64=1.0.0
E: Error occurred while processing package (NewVersion2)
E: Problem with MergeList /data/data/com.termux/files/usr/var/lib/apt/lists/repotermux.kryptonproject.my.id_dists_termux_sc_binary-aarch64_Packages
E: The package lists or status file could not be parsed or opened.

**Comment by twaik** [comment]
I am pretty sure you must remove files related to `repotermux.kryptonproject.my` from `/data/data/com.termux/files/usr/etc/apt/sources.list.d/` and make `apt -f install`...

**Comment by Kry9toN** [comment]
no this my custom apt repo server make from termux-apt-repo script
